### ISSUE TITLE
2D and 3D in the same script throws error

### ISSUE THREAD

**Issue by garyhodgson** [jscad/openscad-openjscad-translator#1]
The following code throws an exception:

```
square([20, 10]);
cube(10);
```

**TypeError: Object [object Object] has no method 'toCSG' at http://localhost/openscad.net/js/lib/csg.js:5301:26**

My hackish attempt to fix it by adding a toCSG method to the CAG class simply means the 3D component fails to be displayed.  The resulting openjscad looks like: 

```
function main(){
return CAG.rectangle({center: [10,5], radius: [10,5]})
           .union([
                   CSG.cube({center: [5,5,5],radius: [5,5,5], resolution: 16})
           ]);
}; 
```

Reversing the 2D and 3D parts results in another, exception:

```
TypeError: Cannot read property 'length' of undefined
    at Object.CSG.mayOverlap (http://localhost/openscad.net/js/lib/csg.js:833:53)
    at Object.CSG.unionSub (http://localhost/openscad.net/js/lib/csg.js:236:15)
    at Object.CSG.union (http://localhost/openscad.net/js/lib/csg.js:230:23)
```

**Comment by z3dev** [comment]
This will not be fixed. Please reopen issues at OpenJSCAD.org
