### ISSUE TITLE
Remove dependency on node-sylvester

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/openscad-openjscad-translator#20]
- node-sylvester has optional dependencies on `lapack` which currently breaks builds
- node-sylvester is only used in a very limited manner in this repository
- node-sylvester [is not compatible with browserify](https://github.com/NaturalNode/node-sylvester/issues/4)  which we use to generate browser builds of openjscad.org 
So we need to swap it out with an acceptable alternative with less issues.

**Comment by johnwebbcole** [comment]
Would it be possible to publish `github:kaosat-dev/node-sylvester` to npm?  I'm loading `@jscad/cli` and `@jscad/web` in a cicd file that uses the `node:lts-alpine` docker image.

Git is not part of the default alpine image, so npm install throws an error loading the `github:kaosat-dev/node-sylvester` package.

```
~/test # npm install @jscad/cli
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/kaosat-dev/node-sylvester.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-29T20_48_28_800Z-debug.log
```

A workaround is to add git with `apk add git` in the cicd file.

**Comment by kaosat-dev** [comment]
@johnwebbcole ahh yes ! it was not the best move to keep it on git only, I hoped it would be removed a long time ago haha :D 
I will ping you once I have it on npm , would that suffice or would you require updated packages for cli & web ?
(Normally we said we where not going to do changes to V1 but this might still be a good case IF reaaly needed)

FYI For V2 node-sylvester has already been removed (but pending rewrite for that specific part that still uses is).

**Comment by kaosat-dev** [comment]
@johnwebbcole now published to https://www.npmjs.com/package/@kaosat-dev/sylvester

**Comment by johnwebbcole** [comment]
@kaosat-dev Great! Thanks.  I think `openscad-openjscad-translator` will need to be updated with the new dependency reference, along with `@jscad/cli` and `@jscad/web` since these are pinned to version `0.0.10` of `openscad-openjscad-translator`.

**Comment by kaosat-dev** [comment]
hmm that is a bit more complicated to be honest for cli & web, that might take a bit more time sorry @johnwebbcole  :( I will still try but no guarantees.

**Comment by z3dev** [comment]
This will not be fixed. Please reopen issues at OpenJSCAD.org
