### ISSUE TITLE
Successor of openscad-openjscad-translator

### ISSUE THREAD

**Issue by techkey** [jscad/openscad-openjscad-translator#3]
Hi, do you happen to know what and where the successor is of openscad-openjscad-translator?

I did try to search but couldn't find the source, probably I'm looking in the wrong direction.

Thanks in advance for your reply,

Cornelis.

**Comment by garyhodgson** [comment]
Hi,

I'm not aware of anyone writing a successor, but then I haven't been involved in the 3D printing world for a few months.  The most active javascript based tools are CoffeeSCAD and OpenJScad as far as I can tell.

Best regards,
Gary
