### ISSUE TITLE
OpenSCAD parser has been changed for variables 

### ISSUE THREAD

**Issue by yoderjen** [jscad/openscad-openjscad-translator#4]
OpenSCAD now allows variables to be declared in any scope, not just in the global scope and at the top of a module's scope.  Any plans to update this parser?  Or hints of where to start in the code to change this?

**Comment by garyhodgson** [comment]
Hi,

No plans from me to make any updates, and to be honest I haven't looked at the code in nearly two years so I can't say where to apply the change.  You'd have to look at openscad-parser.jison I guess and work it out from there.

I used the original OpenSCAD code to work out the parser originally, but considering OpenSCAD has been further developed in the meantime I couldn't say if this would help any.

Best of luck!

Regards,
Gary
