### ISSUE TITLE
I cannot rebuild the parser

### ISSUE THREAD

**Issue by yoderjen** [jscad/openscad-openjscad-translator#5]
I'm trying to edit the parser and cannot successfully build the original (before making any changes).  Help!

Downloading a fresh copy of openscad-openjscad-translator I can run build-web.js and it works perfectly.  If I run jison-build.sh  (version 0.4.17 of Jison) I get this error:

Conflict in grammar: multiple actions possible when lookahead token is TOK_ELSE
in state 19
- reduce by rule: ifelse_statement -> if_statement
- shift token (then go to state 35)

States with conflicts:
State 19
  ifelse_statement -> if_statement . #lookaheads= $end ; { TOK_ID ! # % \* TOK_IF
 TOK_FUNCTION BR TOK_MODULE } TOK_ELSE
  ifelse_statement -> if_statement .TOK_ELSE children_instantiation #lookaheads=
 $end ; { TOK_ID ! # % \* TOK_IF TOK_FUNCTION BR TOK_MODULE } TOK_ELSE

Is this a version problem with jison?  Any idea what version I should be targeting?

**Comment by kaosat-dev** [comment]
@yoderjen that is actually only a warning ! I had the same issue, and also this translator has now been upgraded (see latest commits etc)
