### ISSUE TITLE
Update README and LICENSE

### ISSUE THREAD

**Issue by z3dev** [jscad/openscad-openjscad-translator#8]
Given that the owner has very generously provided this library to the JSCAD organization, we should update the readme and license information accordingly, and make this MIT.

Currently, it seems that this project is dead. Not true.

**Comment by kaosat-dev** [comment]
Totally missed this, sorry @z3dev  ! 
I think we cannot change the License since it is based on Openscad , but I agree that the README needs an upgrade.

**Comment by z3dev** [comment]
Hmm... I don't think that the translator contains any of the original code from OpenSCAD. The GPLv3 only applies if any part of the original "program" is being used.

If not then the license can be anything deemed necessary for this project.

**Comment by kaosat-dev** [comment]
Ok agreed!
